import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	alias: {
		"@": "./src"
	},
	// Svelte 5 编译插件
	plugins: [
		sveltePlugin({
			preprocess: sveltePreprocess(),
			compilerOptions: {
				// 生产模式下启用 CSS 注入，开发模式下也注入（单文件输出）
				css: "injected",
			},
		}),
	],
	// 确保 .svelte 文件中的路径别名正确解析
	mainFields: ["svelte", "browser", "module", "main"],
	conditions: ["svelte", "browser"],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
